//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string patronymic { get; set; }
        public string position { get; set; }
        public string phone_number { get; set; }
        public int age { get; set; }
        public string direction_of_development { get; set; }
    }
}
